INSERT INTO INSTRUCTOR (NAME)  VALUES ('Zebbe');
INSERT INTO INSTRUCTOR (NAME)  VALUES ('Zara');

INSERT INTO WORKOUT (NAME, TYPE_OF_WORKOUT, INSTRUCTOR_ID, LOCATION, PARTICIPANTS, PRICE_SEK, DATE)  VALUES ('Yin Yoga', 'Yoga',2,'Stora salen',22, 200, '2025-06-22');
INSERT INTO WORKOUT (NAME, TYPE_OF_WORKOUT, INSTRUCTOR_ID, LOCATION, PARTICIPANTS, PRICE_SEK, DATE)  VALUES ('Fun run', 'Cardio',1, 'Ute',12, 200, '2025-09-22');

INSERT INTO SPECIALITY (NAME, SKILL_LEVEL, INSTRUCTOR_ID ) VALUES ('YOGA', '5', 2);
INSERT INTO SPECIALITY (NAME, SKILL_LEVEL, INSTRUCTOR_ID ) VALUES ('CARDIO', '4', 1);

INSERT INTO BOOKING (BOOKING_DATE, CUSTOMER_USERNAME, WORKOUT_ID, TOTAL_PRICE )  VALUES ('2025-06-22','Anna', 1, 200);
INSERT INTO BOOKING (BOOKING_DATE, CUSTOMER_USERNAME, WORKOUT_ID, TOTAL_PRICE )  VALUES ('2025-06-22','Maria', 2, 200);